import { NextResponse } from 'next/server'
import supabase from '../../../lib/supabaseAdmin'

const mockBusinesses = [
  // Featured businesses from island pages
  {id:'sealink-ferry', slug:'sealink-ferry', name:'Sealink Ferry Service', category:'Transport & Ferry', description:'Sealink provides daily passenger and vehicle ferry services to Southern Moreton Bay Islands including Russell, Macleay, Lamb, and Karragarra Islands. Our modern fleet operates year-round with multiple daily departures from Redland Bay terminal. Online booking available for convenience. Check our website for current timetables, fares, and special offers. Vehicle bookings essential during peak periods.', phone:'13 32 24', email:'info@sealinkqld.com.au', website:'https://www.sealinkqld.com.au', address:'Redland Bay Marina, Weinam Creek Road, Redland Bay QLD 4165', hours:'Daily services from 5:30am to 11:30pm\nOffice: Mon-Fri 8am-5pm\nWeekend phone enquiries available', location:'Redland Bay', status:'featured'},
  {id:'redland-hospital', slug:'redland-hospital', name:'Redland Hospital', category:'Health & Medical', description:'Redland Hospital is the major public hospital serving the Redlands Coast and Southern Moreton Bay Islands. We provide 24/7 emergency services, surgical services, maternity care, medical imaging, pathology, and specialist outpatient clinics. Our dedicated team serves island residents with helicopter emergency transfers when needed. General practice services available weekdays, emergency department always open.', phone:'07 3488 6111', email:'redland_hospital@health.qld.gov.au', website:'https://www.health.qld.gov.au/redland', address:'Weippin Street, Cleveland QLD 4163', hours:'Emergency Department: 24 hours, 7 days\nOutpatient Clinics: Mon-Fri 8am-5pm\nVisiting Hours: Daily 10am-8pm', location:'Cleveland', status:'featured'},
  {id:'russell-bowls-club', slug:'russell-bowls-club', name:'Russell Island Bowls Club', category:'Sports & Recreation', description:'Russell Island Bowls Club is the heart of island community life. We welcome members and visitors for barefoot bowls, social events, and competitions. Our club features a well-maintained green, licensed bar, bistro meals on weekends, and regular social events including trivia nights and live music. Join us for Friday night raffles, Sunday afternoon bowls, or become a member to enjoy all our facilities. New players always welcome with coaching available.', phone:'07 3409 7766', email:'info@russellbowls.com.au', website:'https://russellbowls.com.au', address:'12 Coonyan Road, Russell Island QLD 4184', hours:'Wed-Sun: 10am-8pm\nBowls: Wed 1pm, Fri 6pm, Sun 2pm\nBistro: Fri-Sun 5pm-7:30pm', location:'Russell Island', status:'featured'},
  {id:'russell-island-school', slug:'russell-island-school', name:'Russell Island State School', category:'Education & Schools', description:'Russell Island State School provides quality primary education from Prep to Year 6 for island children. We are a small, friendly school with dedicated teachers, modern facilities, and a strong community focus. Our curriculum includes literacy, numeracy, science, arts, and physical education. We run breakfast club, homework support, and extracurricular activities. Enrolments welcome year-round. School bus service available from ferry terminal.', phone:'07 3409 8222', email:'principal@russellss.eq.edu.au', website:'https://russellss.eq.edu.au', address:'23 Prompton Street, Russell Island QLD 4184', hours:'School Hours: Mon-Fri 8:30am-3pm\nOffice: Mon-Fri 8am-3:30pm\nBefore School Care: 7am-8:30am', location:'Russell Island', status:'claimed'},
  {id:'macleay-bowls-club', slug:'macleay-bowls-club', name:'Macleay Island Bowls Club', category:'Sports & Recreation', description:'Macleay Island Bowls Club offers competitive and social lawn bowls in a friendly island atmosphere. Our championship green hosts weekly competitions, barefoot bowls events, and social gatherings. Full bar service, bistro meals, poker machines, and TAB facilities. Members enjoy discounted green fees, bar prices, and access to reciprocal clubs across Queensland. Coaching available for beginners. Join us for our famous Sunday sausage sizzle!', phone:'07 3409 9944', email:'secretary@macleaybowls.com.au', website:'https://macleaybowls.com.au', address:'38 Russell Street, Macleay Island QLD 4184', hours:'Mon-Thu: 10am-6pm\nFri-Sun: 10am-8pm\nCompetitions: Wed 12pm, Sat 1pm', location:'Macleay Island', status:'featured'},
  {id:'macleay-community-hall', slug:'macleay-community-hall', name:'Macleay Island Community Hall', category:'Community & Events', description:'Macleay Island Community Hall is available for hire for weddings, parties, meetings, workshops, and community events. Our spacious hall accommodates up to 150 people with commercial kitchen facilities, tables, chairs, sound system, and air conditioning. Regular community events include markets, fitness classes, craft groups, and island council meetings. Competitive hire rates with discounts for local residents and non-profit organizations.', phone:'0411 234 567', email:'bookings@macleayhall.org.au', website:'https://macleayhall.org.au', address:'15 High Central Road, Macleay Island QLD 4184', hours:'Hall available 7 days for hire\nBooking Office: Mon, Wed, Fri 9am-2pm\nCommunity Markets: 2nd Sunday monthly 8am-12pm', location:'Macleay Island', status:'claimed'},
  {id:'lamb-community-hall', slug:'lamb-community-hall', name:'Lamb Island Community Hall', category:'Community & Events', description:'Lamb Island Community Hall serves as the central gathering place for our island community. Available for private hire for birthday parties, anniversaries, meetings, and celebrations. The hall features kitchen facilities, outdoor covered area, and parking. Home to regular community events including monthly markets, craft mornings, yoga classes, and community association meetings. Affordable hire rates for island residents.', phone:'0422 567 890', email:'lambhall@gmail.com', address:'8 Lamb Island Esplanade, Lamb Island QLD 4184', hours:'Available for hire 7 days\nEnquiries: Mon-Fri 9am-5pm\nMonthly Markets: 3rd Saturday 7am-11am', location:'Lamb Island', status:'claimed'},
  {id:'karragarra-community-hall', slug:'karragarra-community-hall', name:'Karragarra Island Community Hall', category:'Community & Events', description:'Karragarra Island Community Hall is the heart of our small, close-knit island community. The hall hosts regular community gatherings, emergency meetings, social events, and is available for private hire. Basic kitchen and BBQ facilities available. Our hall is used for island planning meetings, celebrations, and community support services. Bookings managed by the Karragarra Island Community Association. All island residents welcome to use facilities.', phone:'0433 789 012', email:'karragarraisland@outlook.com', address:'Karragarra Island Road, Karragarra Island QLD 4184', hours:'Available for hire by arrangement\nCommunity meetings: 1st Monday monthly 6pm\nContact KICA for bookings', location:'Karragarra Island', status:'claimed'},
  // Mainland placeholders – marked unclaimed so locals can claim
  {id:'redland-bay-marine-services', slug:'redland-bay-marine-services', name:'Redland Bay Marine Services', category:'Marine & Water Sports', description:'Boat repairs, servicing, outboard diagnostics, antifouling, and trailer repairs beside Weinam Creek. Ready for owners to claim and update.', phone:'07 3200 8801', email:'info@rbmarine.com.au', address:'2 Meissner Street, Redland Bay QLD 4165', location:'Redland Bay', hours:'Mon-Fri 8am-5pm\nSat 8am-1pm', status:'unclaimed'},
  {id:'victoria-point-cinemas', slug:'victoria-point-cinemas', name:'Victoria Point Cinemas', category:'Hospitality & Tourism', description:'Local cinema and dining precinct at Victoria Point Lakeside. Owners can claim this listing to add session times and offers.', phone:'07 3829 8100', email:'hello@vp-cinemas.com.au', address:'325-327 Colburn Ave, Victoria Point QLD 4165', location:'Victoria Point', status:'unclaimed'},
  {id:'cleveland-library', slug:'cleveland-library', name:'Cleveland Library', category:'Community & Events', description:'Public library, study rooms, kids programs, meeting rooms. Claim to manage events and opening hours.', phone:'07 3829 8576', email:'library@redland.qld.gov.au', address:'60-70 Bloomfield St, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'cleveland-mall', slug:'cleveland-mall', name:'Cleveland Central & Mall', category:'Retail & Shopping', description:'Shopping, dining, services near the hospital and council. Placeholder listing ready for centre management to claim.', phone:'07 3821 1233', email:'info@clevelandmall.com.au', address:'90 Middle St, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'capalaba-central', slug:'capalaba-central', name:'Capalaba Central Shopping Centre', category:'Retail & Shopping', description:'Major retail centre with supermarkets, fashion, dining, and cinema. Centre management can claim to add store directory.', phone:'07 3390 2033', email:'hello@capalabacentral.com.au', address:'38 Moreton Bay Rd, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'capalaba-medical-centre', slug:'capalaba-medical-centre', name:'Capalaba Medical Centre', category:'Health & Medical', description:'GP clinic, pathology, allied health. Placeholder for practice managers to claim and update providers.', phone:'07 3245 6000', email:'reception@capmed.com.au', address:'200 Old Cleveland Rd, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'victoria-point-pharmacy', slug:'victoria-point-pharmacy', name:'Victoria Point Pharmacy', category:'Pharmacy', description:'Community pharmacy near the lakeside precinct. Claim to add opening hours and scripts-on-file services.', phone:'07 3820 1000', email:'hello@vppharmacy.com.au', address:'Shop 12, Lakeside Shopping Centre, Victoria Point QLD 4165', location:'Victoria Point', status:'unclaimed'},
  {id:'cleveland-rsl', slug:'cleveland-rsl', name:'Cleveland RSL Club', category:'Hospitality & Tourism', description:'Dining, bar, entertainment, veterans services. Placeholder for club managers to claim.', phone:'07 3488 1100', email:'info@clevelandrsl.com.au', address:'Cnr Shore & Passage St, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'cleveland-coastal-dining', slug:'cleveland-coastal-dining', name:'Cleveland Coastal Dining', category:'Restaurants', description:'Waterfront restaurant and bar. Owners can claim to add menus, hours, and specials.', phone:'07 3821 7777', email:'bookings@clevelandcoastal.com.au', address:'152 Shore St W, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'capalaba-bunnings', slug:'capalaba-bunnings', name:'Bunnings Capalaba', category:'Home & Garden', description:'Hardware, garden centre, trade supplies. Placeholder ready for store to claim.', phone:'07 3513 4400', email:'info@bunnings.com.au', address:'67-69 Redland Bay Rd, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'capalaba-vet', slug:'capalaba-vet', name:'Capalaba Veterinary Clinic', category:'Pets & Vets', description:'Local vet clinic providing consultations, vaccinations, surgery, and pet advice. Claim to update hours.', phone:'07 3245 3003', email:'info@capvet.com.au', address:'200 Old Cleveland Rd, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'redland-bay-marine-fuel', slug:'redland-bay-marine-fuel', name:'Redland Bay Marine Fuel & Chandlery', category:'Automotive & Fuel', description:'Fuel dock, ice, bait, chandlery, and safety gear by the marina. Claim to manage pricing and hours.', phone:'07 3206 0225', email:'fuel@rbmarina.com.au', address:'Weinam Creek Rd, Redland Bay QLD 4165', location:'Redland Bay', status:'unclaimed'},
  {id:'victoria-point-childcare', slug:'victoria-point-childcare', name:'Victoria Point Early Learning', category:'Childcare & Early Learning', description:'Long day care and kindergarten program. Placeholder for centre to claim and publish vacancies.', phone:'07 3207 4000', email:'info@vpearlylearning.com.au', address:'21 School Rd, Victoria Point QLD 4165', location:'Victoria Point', status:'unclaimed'},
  {id:'cleveland-physio', slug:'cleveland-physio', name:'Cleveland Physio & Sports Injury Clinic', category:'Health & Medical', description:'Physiotherapy, sports rehab, pilates. Claim to add practitioner profiles and booking links.', phone:'07 3286 1234', email:'hello@clevelandphysio.com.au', address:'120 Bloomfield St, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'russell-island-iga', slug:'russell-island-iga', name:'IGA Russell Island', category:'Groceries & Convenience', description:'Local supermarket stocking fresh produce, pantry staples, and island essentials. Claim to add specials and hours.', address:'61 High St, Russell Island QLD 4184', location:'Russell Island', status:'unclaimed'},
  {id:'macleay-island-sports-club', slug:'macleay-island-sports-club', name:'Macleay Island Sports Club', category:'Sports & Recreation', description:'Community sports fields and clubhouse. Claim to publish fixtures and memberships.', address:'9 Russell Terrace, Macleay Island QLD 4184', location:'Macleay Island', status:'unclaimed'},
  {id:'victoria-point-bulk-billing-medical', slug:'victoria-point-bulk-billing-medical', name:'Victoria Point Bulk Billing Medical', category:'Health & Medical', description:'Bulk billing GP clinic near the lakeside precinct. Claim to add doctors and online bookings.', address:'325-327 Colburn Ave, Victoria Point QLD 4165', location:'Victoria Point', status:'unclaimed'},
  {id:'redland-bay-post-office', slug:'redland-bay-post-office', name:'Redland Bay Post Office', category:'Government & Council', description:'Postal services, PO boxes, bill payments. Claim to update hours and services.', address:'149 Broadwater Terrace, Redland Bay QLD 4165', location:'Redland Bay', status:'unclaimed'},
  {id:'cleveland-train-station', slug:'cleveland-train-station', name:'Cleveland Train Station', category:'Transport & Ferry', description:'Terminal station on the Cleveland line connecting to Brisbane CBD. Claim to add amenities and parking info.', address:'Shore St W, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'capalaba-bus-interchange', slug:'capalaba-bus-interchange', name:'Capalaba Bus Interchange', category:'Transport & Ferry', description:'Regional bus hub connecting Capalaba, Carindale, and Redlands. Claim to add routes and timetable links.', address:'Redland Bay Rd, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'wellington-point-jetty-cafe', slug:'wellington-point-jetty-cafe', name:'Wellington Point Jetty Cafe', category:'Cafe & Food', description:'Waterfront cafe with coffee, breakfast, and fish & chips. Claim to add menu and trading hours.', address:'2A Main Rd, Wellington Point QLD 4160', location:'Wellington Point', status:'unclaimed'},
  {id:'capalaba-tyre-and-auto', slug:'capalaba-tyre-and-auto', name:'Capalaba Tyre & Auto', category:'Automotive & Fuel', description:'Tyres, logbook servicing, brakes, and suspension. Claim to add pricing and bookings.', address:'100 Old Cleveland Rd, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'cleveland-legal-services', slug:'cleveland-legal-services', name:'Cleveland Legal Services', category:'Professional Services', description:'Local solicitors for conveyancing, wills, and small business. Claim to add lawyer profiles.', address:'120 Bloomfield St, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'victoria-point-real-estate', slug:'victoria-point-real-estate', name:'Victoria Point Real Estate', category:'Real Estate & Property', description:'Residential sales and property management. Claim to add listings and agent contacts.', address:'5 Lakeside Blvd, Victoria Point QLD 4165', location:'Victoria Point', status:'unclaimed'},
  {id:'redland-bay-plumbing', slug:'redland-bay-plumbing', name:'Redland Bay Plumbing & Gas', category:'Trades & Services', description:'Emergency plumbing, hot water, and gas fitting. Claim to add call-out hours.', address:'Redland Bay QLD', location:'Redland Bay', status:'unclaimed'},
  {id:'russell-island-handyman', slug:'russell-island-handyman', name:'Russell Island Handyman', category:'Trades & Services', description:'Local handyman for repairs, gardens, and maintenance. Claim to add rates and availability.', address:'Russell Island QLD', location:'Russell Island', status:'unclaimed'},
  {id:'macleay-island-garden-centre', slug:'macleay-island-garden-centre', name:'Macleay Island Garden Centre', category:'Home & Garden', description:'Plants, soil, mulch, and garden advice. Claim to add delivery options.', address:'High Central Rd, Macleay Island QLD 4184', location:'Macleay Island', status:'unclaimed'},
  {id:'wellington-point-surf-life-saving', slug:'wellington-point-surf-life-saving', name:'Wellington Point Surf Life Saving Supporters', category:'Community & Events', description:'Community surf life saving supporters club. Claim to list events and memberships.', address:'Wellington Point Recreation Reserve, QLD 4160', location:'Wellington Point', status:'unclaimed'},
  {id:'cleveland-markets', slug:'cleveland-markets', name:'Cleveland Markets', category:'Community & Events', description:'Sunday markets with produce, crafts, and food. Claim to publish stallholder info.', address:'Bloomfield St, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'victoria-point-bowls', slug:'victoria-point-bowls', name:'Victoria Point Bowls & Recreation Club', category:'Sports & Recreation', description:'Lawn bowls, social events, and bistro. Claim to add competitions and menus.', address:'3 Poinciana Ave, Victoria Point QLD 4165', location:'Victoria Point', status:'unclaimed'},
  {id:'cleveland-harbour-dining', slug:'cleveland-harbour-dining', name:'Cleveland Harbour Dining Precinct', category:'Restaurants', description:'Mix of restaurants and bars at Raby Bay Harbour. Claim to add menus and events.', address:'Shore St W, Cleveland QLD 4163', location:'Cleveland', status:'unclaimed'},
  {id:'capalaba-crossfit', slug:'capalaba-crossfit', name:'CrossFit Capalaba', category:'Sports & Recreation', description:'Strength and conditioning gym. Claim to add timetable and coaching staff.', address:'6 Merritt St, Capalaba QLD 4157', location:'Capalaba', status:'unclaimed'},
  {id:'redland-bay-bottle-shop', slug:'redland-bay-bottle-shop', name:'Redland Bay Cellars', category:'Hospitality & Tourism', description:'Bottle shop with local and craft selections. Claim to add specials and tasting events.', address:'149 Broadwater Terrace, Redland Bay QLD 4165', location:'Redland Bay', status:'unclaimed'},
  {id:'shane-smith-concreting', slug:'shane-smith-concreting', name:'Shane Smith Concreting', category:'Trades & Services', description:'Professional concrete work including driveways, pathways, patios, foundations, and structural concrete. Over 20 years experience serving Bay Islands. Quality craftsmanship, reliable service, competitive pricing. Free quotes. All suburbs covered. Licensed, insured, and bonded.', phone:'0438 123 456', email:'shane@smithconcreting.com.au', website:'https://smithconcreting.com.au', address:'Russell Island, QLD 4184', hours:'Mon-Fri: 7am-5pm\nSat: 8am-12pm\nEmergency jobs available', location:'Russell Island', status:'featured'},
  {id:'steve-sandy-block-clearing', slug:'steve-sandy-block-clearing', name:'Steve & Sandy Block Clearing', category:'Trades & Services', description:'Professional land clearing and excavation services. Remove trees, stumps, rocks, and unwanted vegetation. Perfect for preparing land for building, gardens, or maintenance. Safe, efficient, licensed operators. Russell Island locals serving all Moreton Bay Islands.', phone:'0412 987 654', email:'steve@blockclearedland.com.au', address:'Russell Island, QLD 4184', hours:'Daily available\nQuote enquiries: 7am-6pm', location:'Russell Island', status:'featured'},
  // Original mock businesses
  {id:'1', slug:'island-cafe-bakery', name:'Island Cafe & Bakery', category:'Cafe & Food', description:'Award-winning cafe and bakery. Fresh pastries daily, excellent coffee, local ingredients. Perfect for breakfast and lunch.', phone:'07 3409 1234', email:'info@islandcafe.com.au', website:'https://islandcafe.com.au', address:'15 High Street, Russell Island', hours:'Mon-Fri: 6am-3pm\nSat-Sun: 7am-2pm'},
  {id:'2', slug:'bay-marina-services', name:'Bay Marina Services', category:'Marine & Water Sports', description:'Full-service marina with boat repairs, maintenance, fuel, and equipment rental. Expert mechanics, competitive pricing.', phone:'07 3409 5678', email:'service@baymarina.com.au', website:'https://baymarina.com.au', address:'22 Marina Road, Redland Bay', hours:'Mon-Sat: 7am-6pm\nSun: 8am-4pm'},
  {id:'3', slug:'island-resort-spa', name:'Island Resort & Spa', category:'Hospitality & Tourism', description:'4-star luxury resort with spa, pool, restaurant. Oceanfront suites, wedding venue, conference facilities. Book direct for discounts.', phone:'07 3409 9000', email:'reservations@islandresort.com.au', website:'https://islandresort.com.au', address:'88 Beachfront Drive, Macleay Island', hours:'Check-in: 2pm\nCheck-out: 10am\nReception: 24/7'},
  {id:'4', slug:'the-bay-restaurant', name:'The Bay Restaurant', category:'Fine Dining', description:'Waterfront fine dining. Fresh seafood daily. Award-winning chef. Reservations recommended. Sunset views.', phone:'07 3409 3456', email:'bookings@thebayrestaurant.com.au', website:'https://thebayrestaurant.com.au', address:'45 Sunset Boulevard, Macleay Island', hours:'Dinner: Tue-Sun 5pm-10pm\nClosed Mondays'},
  {id:'5', slug:'blue-water-charters', name:'Blue Water Charters', category:'Marine & Water Sports', description:'Sport fishing charters, snorkeling trips, scenic cruises. Professional captains, safety equipment provided. Half and full-day trips.', phone:'0412 345 678', email:'bookings@bluewatercharters.com.au', website:'https://bluewatercharters.com.au', address:'Redland Bay Marina', hours:'Daily: 5am-8pm (by appointment)'}
]

export async function GET(){
  try {
    const { data, error } = await supabase.from('businesses').select('*').order('name', {ascending:true}).limit(50)
    if(error) return NextResponse.json(data && data.length > 0 ? data : mockBusinesses)
    return NextResponse.json(data && data.length > 0 ? data : mockBusinesses)
  } catch {
    return NextResponse.json(mockBusinesses)
  }
}
