export const businessCategories = [
  'Cafe & Food',
  'Restaurants',
  'Groceries & Convenience',
  'Health & Medical',
  'Pharmacy',
  'Education & Schools',
  'Childcare & Early Learning',
  'Transport & Ferry',
  'Marine & Water Sports',
  'Hospitality & Tourism',
  'Real Estate & Property',
  'Trades & Services',
  'Building & Construction',
  'Professional Services',
  'Community & Events',
  'Sports & Recreation',
  'Retail & Shopping',
  'Automotive & Fuel',
  'Emergency Services',
  'Government & Council',
  'Pets & Vets',
  'Home & Garden'
];
